### ISSUE TITLE
ModuleNotFoundError: No module named 'QCF'

### ISSUE THREAD

**Issue by vascosa** [ccipd/MRQy#3] opened 2021-03-12 23:01 UTC
Hello,

I was getting the ModuleNotFoundError: No module named 'QCF' issue when running the test example `python -m mrqy.QC --help`.

I solved this by going into the virtual environment site-packages and editing line 11 on the QC.py to `import mrqy.QCF as QCF`, which solved my issue. I don't know if you ever run into anything like this. The  package mrqy included both files, but I had to point it to the package itself to import QCF it looks like. I'm on python 3.6.8.

Cheers,
Vasco

**Comment by satishev** [comment] 2021-03-13 00:05
@Amir-Reza-Sadri can double check, maybe some kind of env check may be required.

**Comment by Amir-Reza-Sadri** [comment] 2021-03-23 02:22
The issue has been fixed.

**Comment by giemmecci** [comment] 2022-06-13 19:58
Hi, I'm having the same issue, and the only way to have it working was to change line 11 in the QC.py file, as mentioned by @vascosa.

Thanks

**Comment by satishev** [comment] 2022-06-13 21:28
@giemmecci this issues should have been fixed in an update made to QC.py back in March. Could you check whether you have the latest version of the repo?

**Comment by giemmecci** [comment] 2022-06-14 02:42
> 

Thanks!

I think so; I've downloaded the v2022.04 version of the code; this is the output:

`(mrqyenv) (MRQy-2022.04) redacted@redacted MRQy-2022.04 % python -m mrqy.QC --help
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/redacted/.local/share/virtualenvs/MRQy-2022.04-p-CJzWwa/lib/python3.8/site-packages/mrqy/QC.py", line 11, in <module>
    import QCF
ModuleNotFoundError: No module named 'QCF'`

**Comment by satishev** [comment] 2022-06-14 02:44
@Amir-Reza-Sadri could you check the mentioned package on the releases page and fix as needed?

**Comment by satishev** [comment] 2022-06-20 15:53
@giemmecci please try updating your repo (not released this as a package yet) and seeing if the issue is fixed?

**Comment by giemmecci** [comment] 2022-06-24 22:08
I've re-installed everything from scratch and it works now, thanks!

**Closed** 2022-06-28 04:52 UTC
